/**
 * EnrollmentStatus describes the review state of a registration request.
 */
export type EnrollmentStatus = 'pending' | 'approved' | 'rejected';

/**
 * Enrollment links one student to one course and stores the review state.
 */
export interface Enrollment {
  /** The enrollment id is generated by the application. */
  readonly id: string;

  /** The student who submitted the request. */
  studentId: string;

  /** The course the student selected. */
  courseId: string;

  /** A new request starts as pending and can be reviewed later. */
  status: EnrollmentStatus;
}
